import swiper from "./modules/swiper.js"
import customeVideo from "./modules/customeVideo.js"
import date from "./modules/date.js"

// import * as popup from "./modules/popup.js"
// import * as regularExpressions from "./modules/regularExpressions.js"
// import * as accordion from "./modules/accordion.js"
// import * as swiper from "./modules/swiper.js"
// import * as products from "./modules/products.js"
// import * as date from "./modules/date.js"